// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	kafka "gopkg.in/confluentinc/confluent-kafka-go.v1/kafka"

	mock "github.com/stretchr/testify/mock"
)

// KafkaProducer is an autogenerated mock type for the KafkaProducer type
type KafkaProducer struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *KafkaProducer) Close() {
	_m.Called()
}

// Events provides a mock function with given fields:
func (_m *KafkaProducer) Events() chan kafka.Event {
	ret := _m.Called()

	var r0 chan kafka.Event
	if rf, ok := ret.Get(0).(func() chan kafka.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan kafka.Event)
		}
	}

	return r0
}

// ProduceChannel provides a mock function with given fields:
func (_m *KafkaProducer) ProduceChannel() chan *kafka.Message {
	ret := _m.Called()

	var r0 chan *kafka.Message
	if rf, ok := ret.Get(0).(func() chan *kafka.Message); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *kafka.Message)
		}
	}

	return r0
}
